on: [push]
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    container:
      image: sinixnd/tak:latest
    steps:
      # Clones to $GITHUB_WORKSPACE
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - run: make release cppcheck
